[tool.pyright]
autoSearchPaths = true,
diagnosticMode = "openFilesOnly"
useLibraryCodeForTypes = true

typeCheckingMode = "strict"

reportUnknownMemberType = "none"
reportAny = "none"
reportExplicitAny = "none"
reportImplicitOverride = "none"
reportMissingSuperCall = "none"
reportPrivateLocalImportUsage = "none"
reportUnnecessaryTypeIgnoreComment = "none"
reportIncompatibleMethodOverride = "none"
reportUnusedCallResult = "none"
reportImplicitStringConcatenation = "warning"
reportMissingParameterType = "warning"
reportMissingTypeArgument = "warning"
reportPrivateUsage = "warning"
reportUnknownArgumentType = "warning"
reportUnknownLambdaType = "warning"
reportUnknownParameterType = "warning"
reportUnknownVariableType = "warning"
reportUnnecessaryCast = "warning"
reportUnnecessaryComparison = "warning"
reportUnnecessaryContains = "warning"
reportUnnecessaryIsInstance = "warning"
reportUntypedBaseClass = "warning"
reportUntypedClassDecorator = "warning"
reportUntypedFunctionDecorator = "warning"
reportUntypedNamedTuple = "warning"
reportUnusedClass = "warning"
reportUnusedExpression = "warning"
reportUnusedFunction = "warning"
reportUnusedImport = "warning"
reportUnusedVariable = "warning"
reportCallInDefaultInitializer = "error"
reportDuplicateImport = "error"
reportUninitializedInstanceVariable = "error"
reportUnreachable = "error"
